### PR TITLE
Print a summary over all test cases

### PR DESCRIPTION
**Pull request by breml**
including:
* total messages
* match successful
* match failed
* missing messages

### CODE REVIEW

**Comment by magnusbaeck** [comment]
Sorry for dragging my feet with this one. Instead of adding more logic and state to the existing code I hope we can use an observer pattern for test results so that today's progress output, this summary information, the JUnit XML files described in #6, and whatever else we can come up with, each can be implemented independently and outside the main code path.

The core code would then report its progress to the zero, one, or more TestResultProcessor pointers that it's given upon initialization and let those entities worry about what to echo to the terminal, write to files, or whatever. What do you think about that idea?

**Comment by breml** [comment]
@magnusbaeck This sounds reasonable and will lead to much cleaner code in the sense, that the main logic and reporting logic will not be such tightly coupled anymore. I guess, this proposal also has the potential to remove some of the currently existing duplicated code. Will you create a first iteration towards this direction?

**Comment by magnusbaeck** [comment]
> This sounds reasonable and will lead to much cleaner code in the sense, that the main logic and reporting logic will not be such tightly coupled anymore. I guess, this proposal also has the potential to remove some of the currently existing duplicated code.

Yes, hopefully.

> Will you create a first iteration towards this direction?

I can do that, but I probably won't be able to do it for a couple of weeks.

**Comment by breml** [comment]
Maybe we should create a new issue for this refactoring.

**Comment by magnusbaeck** [comment]
> Maybe we should create a new issue for this refactoring.

Yes; filed as #46.

**Comment by breml** [comment]
@magnusbaeck I close this PR. It has been resolved as part of #74.

**Pull request closed without merging**
