### PR TITLE
Make wait-for-late-arrivals-timeout configurable

### PR DESCRIPTION
**Pull request by breml**
Fixes: #168

### CODE REVIEW

**Comment by breml** [comment]
@magnusbaeck Some of the "constructors" have really long argument lists by now, so this should be refactored. Maybe I find some time at the end of the month to have a look at this.

**Review by magnusbaeck — APPROVED** [review]
> Some of the "constructors" have really long argument lists by now, so this should be refactored. Maybe I find some time at the end of the month to have a look at this.

SGTM. Replacing the args with a TimeoutConfig struct, or did you have anything else in mind?

**Comment by breml** [comment]
I see two options to address the long argument lists for the constructors:

1. Config struct
2. Functional options

(see: https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis)

I personally like the functional options approach very much.

**Comment by magnusbaeck** [comment]
Ah yes, functional options are quite nice. Incidentally I implemented them in https://github.com/eiffel-community/eiffelevents-sdk-go/pull/16 just a few days ago.

**Pull request merged**
